In [1]:
# Q. 입력값으로 Abc, ABC, abc 등으로 입력하는 경우 모두 처리할 수 있도록 코드를 수정하세요.
c = input('소문자 abc를 입력하세요> ')
if c == 'abc':
    print('잘 처리되었습니다.')
else: print('처리가 되지 않았습니다.')

소문자 abc를 입력하세요> ㄴㅇㄹ
처리가 되지 않았습니다.

In [4]:
# 수정
c = input("소문자 abc를 입력하세요.").lower()
if c == "abc":
    print("잘 처리되었습니다.")
else:
    print("처리가 되지 않았습니다.")

소문자 abc를 입력하세요.ABC
잘 처리되었습니다.

In [7]:
# List안의 단어가 있으면 해당 제목을 출력
x = input("제목을 입력해주세요: ")
tlist = ['Hello Word!', 'Nice Day','HappyBin','enDing_Story']
n_tlist = []

x=x.lower()
for i in range(len(tlist)):
    n_tlist.append(tlist[i].lower())
    if x in n_tlist[i]:
        print(tlist[i])

제목을 입력해주세요: day
Nice Day

In [9]:
# 문자열에서 좌우 공백 제거
txt = '   양쪽에 공백이 있는 문자열입니다.  '
ret1 = txt.lstrip()   #문자열 왼쪽 공백 제거
ret2 = txt.rstrip()   #문자열 오른쪽 공백 제거
ret3 = txt.strip()    #문자열 양 옆의 공백 제거
print('<'+ret1+'>')
print('<'+ret2+'>')
print('<'+ret3+'>')

<양쪽에 공백이 있는 문자열입니다.  >
<   양쪽에 공백이 있는 문자열입니다.>
<양쪽에 공백이 있는 문자열입니다.>

In [14]:
# 문자열에서 특정 문자(열) 위치 찾기
txt = 'A lot of things occur each day, every day, all day'
offset1 = txt.find('o')  # 문자열에서 첫번째 'o' 찾아서 문자열 위치 인덱스 반환
offset2 = txt.find('o',4) # 문자열 인덱스 위치 4 에서부터 'o'를 찾아서 문자열 위치 인덱스 반환
offset3 = txt.find('day')
offset4 = txt.find('day',30)
print(offset1)
print(offset2)
print(offset3)
print(offset4)
print(offset5)
len(txt)

3
6
27
38
38

42

In [20]:
# 특정 문자로 결합 #######################
loglist = ['2016/08/26 10:12:11','200','OK','이 또한 지나가리라']
bond = ', '
log = bond.join(loglist)
print(log)

2016/08/26 10:12:11, 200, OK, 이 또한 지나가리라

In [24]:
# 특정 문자(열)을 다른 문자(열)로 바꾸기(replace)
txt = 'My password is 1234'
ret1 = txt.replace('1','0')
ret2 = txt.replace('1','python')

print(ret1)
print(ret2)

txt = '매일 많은 일들이 일어납니다.'

ret3 = txt.replace("많은 일들이", "아침 일찍")
print(ret3)

My password is 0234
My password is python234
매일 아침 일찍 일어납니다.

In [28]:
# 코드값에 대응하는 문자 얻기
while 1:
    val = int(input('문자 코드값을 입력하세요: '))
    ch = chr(val)
    print('코드값: %d 문자: %s' %(val, ch))
    
    next_val = input('계속 하시겠습니까? y,n >>> ')
    if next_val == 'n':
        break

문자 코드값을 입력하세요: 90
코드값: 90 문자: Z
계속 하시겠습니까? y,n >>>y
문자 코드값을 입력하세요: 50
코드값: 50 문자: 2
계속 하시겠습니까? y,n >>>n

In [32]:
# 문자열을 바이트 객체로 바꾸기 (encode)
u_txt = 'I love pyhton'
b_txt = u_txt.encode()

print(u_txt)
print(b_txt)  #b'I love pyhton'  출력하면 표현은 이렇게 되는데,  이 말은 b  즉 바이트 객체라는 말임.

ret1 = 'I' == u_txt[0]
ret2 = 'I' == b_txt[0]
print(u_txt[0])
print(b_txt[0])
print(ret1)
print(ret2)

I love pyhton
b'I love pyhton'
I
73
True
False

In [33]:
# 바이트 객체를 문자열로 바꾸기
b_txt = b'A lot of things occur each day.'
u_txt = b_txt.decode()
print(u_txt)

A lot of things occur each day.

In [34]:
# 인자를 바꾸어 함수를 반복 호출하는 결과값 얻기(map)
f = lambda x: x*x
args = [1,2,3,4,5]
ret = map(f, args) #########
print(list(ret))

[1, 4, 9, 16, 25]

In [35]:
li = []
f = lambda x: x*x
args = [1,2,3,4,5]
ret = map(f, args)
for i in ret:
    li.append(i)
print(li)

[1, 4, 9, 16, 25]

In [36]:
# [3::-1] 과 같이 출력하면 3번 인덱스부터 0번 인덱스까지 역순으로 출력해준다.
s = 'abcde'
print(s[3:0:-1]) #dcb

dcb

In [38]:
print(s[4::-1])  # edcba
print(s[4:0:-1])
print(s[::-1])   # edcba

edcba
edcb
edcba

#### Python random 모듈 
Python의 표준 라이브러리 중 하나로, 다양한 유형의 무작위 데이터를 생성하기 위한 함수와 도구들을 제공합니다. 여기에는 단일 숫자, 숫자 범위, 무작위 순서로 요소를 선택하거나 배열을 섞는 기능 등이 포함
1. random.random() : 0.0에서부터 1.0 사이의 실수(float)를 반환. 0은 포함되고 1은 포함되지 않음
2. random.uniform(a, b) : 인자로 들어온 a~b 사이의 실수(float)를 반환
3. randint(a, b) : 인자로 들어온 a, b 사이의 랜덤한 정수(int)를 반환
4. randrange(a, b), randrange(b) :  a <= x < b 의 범위 내에서의 랜덤한 정수(int)를 반환, randrange(b)는 0 <= x < b 의 범위 내에서의 랜덤한 정수(int)를 반환
5. random.choice(seq) : 인자로 받은 리스트, 튜플, 문자열, range 에서 무작위로 하나의 원소 반환
6. random.sample(seq or set, N) : 첫번째 인자로 받은 시퀀스데이터 or set에서 N개의 랜덤하고, unique하고, 순서상관없이 인자를 뽑아서 리스트로 만들어서 반환. 예: random.sample([1, 2, 3, 4, 5], 3)은 5개의 숫자 중 3개를 임의로 선택한 리스트를 반환
7. random.shuffle(seq) : 데이터의 순서를 무작위로 랜덤하게 바꾸어 주는 함수

In [ ]:
random.random()  # Random float x, 0.0 <= < 1.0

In [39]:
import random
print(random.random())

0.40584030094600176

In [ ]:
random.uniform(1,10) # Random float x, 1.0 <= < 10.0

In [42]:
import random
random.uniform(1,10)

4.649430399691481

In [58]:
import random
print(random.randint(1,10)) # integer from 1 to 10, endpoints included

10

In [ ]:
random.randrange(0,101,2) # Even integer from 0 to 100 여기서 2는 스텝이다 그래서 0 2 4 6 8... 이런식이다.

In [61]:
import random
random.randrange(0,10,2) # 0,2,4,6,8 중 하나

8

In [ ]:
random.choice('abcdefghij') # Choose a random element

In [69]:
import random
fruits = ["apple","banana","cherry","date"]
print(random.choice(fruits)) # 예: "cherry"

apple

In [ ]:
random.sample([1,2,3,4,5],3) # Choose 3 elements

In [70]:
import random
print(random.sample([1,2,3,4,5],3)) # 예: [4,1,5]

[5, 1, 3]

In [ ]:
items = [1,2,3,4,5,6,7]
random.shuffle(items)

In [71]:
import random
numbers = [1,2,3,4,5]
random.shuffle(numbers)
print(numbers)

[1, 4, 3, 5, 2]

In [7]:
# Q. random()을 이용해서 0.0에서 100.0 사이의 실수 중에서 난수값을 리턴
import random
random.random()*100

75.15575815313973

In [8]:
# Q. 1부터 100 사이의 임의의 홀수를 출력하세요.
import random
random.randrange(1,101,2)

13

In [13]:
# Q. 1에서 100 사이의 임의의 짝수를 출력하세요.
import random
print(random.randrange(0,101,2))

26

In [12]:
# Q. 1에서 55 사이의 정수 중에서 난수값을 리턴
import random
random.randint(1,55)

18

In [15]:
# Q. [1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9]에서 임의로 3개를 선택하여 출력하세요(중복 불허)
import random
random.sample([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9],3)

[4, 8, 6]

In [19]:
# Q. 주어진 데이터에서 아래와 같이 출력하세요.
m=['a','b','c','d','e']
t=['당첨','꽝']

#d가 당첨되었습니다. 
import random
m_choice = random.choice(m) 
t_choice = random.choice(t) 
print(f"{m_choice}가 {t_choice}{'되었습니다.' if t_choice == t[0] else '입니다.'}")

a가 꽝입니다.

In [20]:
m=['a','b','c','d','e']
t=['당첨','꽝']

random.shuffle(m)
random.shuffle(t)

print(f'{m[0]}가 {t[0]}되었습니다.')

b가 당첨되었습니다.

In [28]:
# Q. a, b 에서 무작위로 뽑은 숫자가 같으면 당첨, 다르면 꽝을 출력하는 프로그램을 작성하세요. (time gap 1.5초)
#첫번째 값:3
#두번째 값:3
#당첨입니다.

import time
a=[1,2,3,4,5]
b=[1,2,3,4,5]

draw_a = random.choice(a)
print(f'첫번째 값:{draw_a}')
time.sleep(1.5)
draw_b = random.choice(b)
print(f'두번째 값:{draw_b}')
time.sleep(1.5)
print('당첨입니다.' if draw_a == draw_b else '꽝입니다.')

첫번째 값:3
두번째 값:3
당첨입니다.

In [29]:
# Q. list[0,1,2,3,4,5,6]을 내림차순으로 출력하세요(2가지 방법)
list1 = [0,1,2,3,4,5,6]
print(list1[::-1])
list1.reverse()
list1

[6, 5, 4, 3, 2, 1, 0]

[6, 5, 4, 3, 2, 1, 0]

In [30]:
# Q. list = ['a','b','c']을 for문을 사용해서 아래와 같이 출력하세요.
# 1번째는 a입니다.
# 2번째는 b입니다.
# 3번째는 c입니다.

list = ['a','b','c']
for i, value in enumerate(list):
    print('{}번째는 {}입니다.'.format(i+1,value))

1번째는 a입니다.
2번째는 b입니다.
3번째는 c입니다.

In [34]:
# Q. join 함수를 이용해서 ['a','b','c']을 아래와 같이 출력하세요.
#a::b::c
print("::".join(['a','b','c']))

a::b::c

In [35]:
# Q. 데이터를 입력하지 않으면 종료되는 코딩을 수행하세요. 단 반복적으로 작업을 수행할 수 있음.
while 1:
    data = input('데이터를 입력해주세요.')
    if not data: break
    print(data)

데이터를 입력해주세요.

In [41]:
# Q. 원의 면적과 둘레의 길이를 구하는 사용자 함수를 작성하여 반지름이 5와 10일때 면적과 둘레를 구하세요.
import math
def area_circumference(r):
    area = math.pi*r*r
    circumference = 2*math.pi*r
    print(f"면적: {round(area)}, 둘레: {round(circumference)}")

area_circumference(5)
area_circumference(10)

면적: 79, 둘레: 31
면적: 314, 둘레: 63

#### re 모듈

- 파이썬에서 정규 표현식(Regular Expressions)을 지원하기 위한 표준 라이브러리.
- 정규 표현식은 텍스트에서 문자열 검색, 매칭, 치환 및 파싱을 할 때 사용하는 강력한 문자열 처리 도구

re 모듈을 사용하여 수행할 수 있는 기본 작업

- re.match(): 문자열의 시작부터 정규식과 일치하는 패턴을 찾습니다. 일치하는 객체를 반환하거나, 일치하는 것이 없으면 None을 반환

- re.search(): 문자열 전체에 걸쳐 정규식과 일치하는 패턴을 찾는다. match와 달리 문자열의 중간부터 일치하는 패턴을 찾을 수도 있고 일치하는 객체를 반환하거나, 일치하는 것이 없으면 None을 반환

- re.findall(): 문자열 내에서 정규식과 일치하는 모든 부분 문자열을 리스트로 반환

- re.finditer(): findall()과 유사하지만, 일치하는 모든 결과를 이터레이터(iterator)로 반환하여 메모리를 절약

- re.sub(): 문자열 내에서 정규식과 일치하는 부분을 다른 문자열로 치환 --> replace 같은 기능

- re.compile(): 정규식 패턴을 컴파일하여 나중에 재사용할 수 있는 정규식 객체를 생성. 이것은 패턴을 여러 번 사용할 때 성능을 최적화하는 데 도움

정규 표현식 패턴은 특수 문자와 시퀀스를 포함할 수 있으며, 복잡한 문자열 처리를 위한 강력한 문법을 제공.
예를 들어, \d는 숫자를, \w는 단어 문자를, .는 거의 모든 문자를 나타낸다(개행 문자는 제외). 대괄호([])는 문자 집합을, 
괄호(())는 그룹을 정의한다. 별표(*), 더하기(+), 물음표(?), 중괄호({}) 등은 일치하는 횟수를 정의.

In [3]:
import re
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']

def clean_string(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]','',value)  ##########
        value = value.title()
        result.append(value)
    return result
clean_string(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [3]:
# Q. 랜덤하게 1000명의 이름, 키와 몸무게 만들기
import random
hanguls = list('영수철민기정현학준주승유빈재인서우성규용')
with open('member.txt','w') as file:
    for i in range(1000):
        name = random.choice(hanguls)+random.choice(hanguls)
        height = random.randrange(140,200)
        weight = random.randrange(40,100)
        file.write(f'{name},{height},{weight}\n')

with open('member.txt') as file:
    data = file.read()
    print(data)

인빈,149,48
철영,155,95
우승,153,94
빈성,179,94
민수,181,97
민용,167,43
철용,141,88
용학,161,51
기재,179,40
준규,166,87
현철,166,56
주현,151,97
학주,146,83
승우,166,80
서준,172,46
준우,193,89
유정,163,95
빈민,176,58
인용,170,50
재민,146,55
인민,144,44
기학,184,64
기주,184,96
정주,152,46
수준,193,87
인현,152,92
재인,167,66
유철,170,40
기인,172,57
학영,157,99
우용,165,92
성수,162,90
수철,158,77
정준,150,90
인준,166,88
재우,158,81
기빈,178,95
주서,192,84
재준,168,73
용규,155,51
철서,183,68
수승,191,89
우재,190,71
용학,166,74
정재,180,56
빈민,189,77
정학,175,76
주우,181,67
빈재,176,95
철학,174,70
현현,179,88
용현,179,64
학준,192,78
규정,193,88
유승,147,95
빈재,184,64
정용,159,51
현승,146,65
빈준,192,65
주서,147,76
민유,173,93
준규,196,42
승인,155,60
재규,154,94
빈승,193,60
수준,178,41
재학,194,69
용현,150,49
민영,153,51
철서,148,81
재규,176,61
기민,183,80
철철,168,61
재영,168,65
유수,145,60
용인,173,65
영서,166,66
유빈,179,83
영정,181,62
인학,199,84
서준,165,71
주빈,196,81
수서,155,75
수유,147,97
수철,193,91
인용,170,52
인수,175,71
영영,189,46
규철,149,78
용서,159,56
규철,180,59
승서,191,66
현재,195,59
규정,189,87
현준,174,75
준서,196,68
민성,179,86
기수,158,72
용규,167,54
준철,158,68
수현,166,62
우재,190,50
재학,154,67
승용,148,87
수용,196,71
재주,171,85
성수,179,50
성성,148,47
인학,140,94
서준,150,89
규성,144,61
규수,145,89
기정,171,74
학주,145,56
주기,150,42
준빈,177,73
정철,167,73
민주,181,59
정용,161,45
주영,144,57
인재,187,91
우승,148,96
주우,167,89
성현,199,56
현학,167,46
서승,161,91
우승,194,95
규성,192,68
서승,197,69
주철,161,81
학유,180,84
학우,182,41
재유,198,59
수빈,144,89
정주,161,54
기우,167,87
빈재,163,44
영영,195,96
서민,181,70
기철,147,83
용수,179,60
유학,173,46
우승,174,88
재유,191,44
수정,184,54
수영,190,98
수영,149,89
용성,160,87
재재,185,91
주재,149,60
수현,169,59
서용,153,85
주준,185,93
기성,157,87
준준,178,57
영현,146,50
서기,181,79
정인,147,87
유영,141,89
영빈,170,42
현승,147,88
승준,199,57
규유,156,47
재정,146,59
재성,196,72
현인,145,96
정우,165,70
규승,152,80
주수,199,42
재철,151,56
준유,164,76
기수,171,87
영영,158,91
주재,186,57
주용,140,77
주학,178,53
수현,154,45
수성,197,96
유재,156,52
승규,196,77
민서,178,99
성영,165,94
영용,165,92
승철,187,58
빈빈,149,92
용학,155,66
빈인,178,58
우빈,165,43
성철,159,51
수유,197,44
준주,193,97
영학,196,92
규성,196,62
영빈,160,98
재성,192,77
승인,190,77
철준,167,82
인성,149,90
준정,145,92
우빈,166,47
기빈,183,64
규인,179,45
학학,159,81
성학,143,73
승규,177,88
서수,148,48
학철,158,65
주기,190,90
우영,177,90
수빈,179,84
서민,165,45
재철,171,44
유유,188,96
준성,175,40
규철,166,75
수수,171,88
현철,155,62
영우,152,77
현성,143,73
수재,164,46
용재,158,83
유용,140,54
기빈,144,75
현빈,194,90
학우,159,44
우승,157,50
기승,163,60
서주,192,55
유규,152,53
우기,191,72
인성,164,50
민유,169,46
유유,177,76
수주,185,59
성성,149,75
민인,187,65
민규,165,83
우현,148,40
수우,144,53
주민,185,47
영인,163,88
영영,195,77
규영,168,97
용준,190,40
승철,170,64
우준,147,72
성영,145,70
규기,155,97
정규,142,82
인재,146,81
인인,147,86
유서,190,74
유영,149,62
서성,184,93
현민,185,79
수인,149,99
민학,145,44
학정,188,61
수성,175,46
유준,183,91
학빈,189,97
수승,188,78
재기,190,43
현준,154,81
철인,151,41
주현,148,65
현민,184,45
서준,189,42
영재,157,87
주기,186,51
주빈,151,97
영수,166,65
서빈,149,51
기서,173,41
정민,191,90
재정,199,76
민기,197,67
빈승,196,52
수철,177,45
수우,163,48
정승,193,60
유학,149,74
규기,150,58
철성,199,55
인철,192,89
빈수,162,83
철민,195,56
용영,167,96
인민,190,91
유정,164,40
정인,162,82
규성,157,79
규주,165,52
준현,199,59
승영,196,66
민기,163,51
철용,154,87
민빈,170,79
정빈,150,94
용재,170,83
인민,170,62
기수,161,42
정철,183,90
유성,165,73
영승,177,70
영유,145,65
주학,181,99
준성,177,96
규민,191,91
주주,197,74
영민,184,97
유용,191,91
기재,177,50
용주,154,40
학학,161,59
현정,166,46
우서,149,48
현영,160,46
승철,144,47
우학,173,95
정용,179,45
성민,169,43
철인,193,87
승성,156,55
유기,165,76
성주,140,57
학현,141,72
빈현,180,94
우인,143,56
유용,186,50
인서,190,60
준영,146,61
정정,143,44
현주,157,49
서영,187,89
재승,173,84
정우,165,61
영영,183,86
서영,183,74
기철,192,57
우유,142,42
수학,188,74
학서,185,58
빈서,163,66
인수,151,71
재재,188,66
인주,175,93
정현,148,40
수준,180,99
서민,164,83
유철,157,70
현영,162,80
수철,154,58
준승,175,51
민현,177,94
민우,165,63
주용,156,40
영학,171,42
영주,154,56
인민,167,80
성현,179,64
정학,187,82
주승,197,50
현승,156,60
민철,186,81
우우,146,94
수승,194,90
규유,170,95
용기,193,72
성유,151,99
우철,151,45
인성,187,43
용정,157,44
학기,170,64
성승,188,94
현승,143,97
규기,189,87
주빈,145,96
철기,186,80
민빈,196,89
서유,147,79
수승,182,89
영수,189,76
준용,173,82
준민,168,71
승빈,160,62
유학,153,63
서주,150,82
우빈,173,97
규주,162,90
성서,151,56
준서,169,51
성정,150,49
현준,140,93
주용,146,53
우현,148,72
성민,180,97
인철,151,46
기유,197,40
정철,163,75
유민,146,63
현규,193,66
인서,190,76
우철,146,90
주승,150,46
수기,143,82
용기,175,89
인재,176,70
승서,177,61
인재,144,67
용규,196,63
빈철,191,98
인용,147,71
학영,179,92
승서,196,85
기빈,154,99
우기,181,60
우주,158,41
빈우,180,50
성성,166,83
인인,168,90
철영,151,49
성성,177,99
학주,180,56
성현,198,72
현정,185,48
용빈,179,79
우서,148,45
재학,194,68
용빈,184,40
서인,170,75
영학,140,60
인준,155,59
주민,169,79
성정,161,72
주기,167,77
정성,172,52
수성,154,59
영민,167,96
서승,172,73
준유,146,75
서용,189,85
우기,171,57
주수,149,57
인우,180,58
유학,140,91
현재,179,80
기용,181,50
성규,185,51
성준,142,85
정현,197,69
주주,182,45
서영,152,58
영인,172,61
기학,164,84
서성,155,90
우유,143,45
서규,194,60
학민,180,48
준서,143,80
승승,185,66
기철,159,97
영주,173,47
성재,166,65
유영,181,99
유우,155,90
현주,184,85
정영,173,97
철현,193,60
용영,165,94
인준,190,93
주승,171,90
정기,177,57
규기,145,87
인철,161,72
학인,183,63
유준,173,52
용서,155,91
성재,178,84
규준,189,80
영용,173,81
정우,165,83
유성,142,49
우주,191,98
우철,162,59
민영,180,49
민수,196,98
영유,154,89
승정,154,86
현승,165,47
우우,170,96
용규,194,87
준수,153,61
유학,192,48
학유,156,46
용규,199,81
영민,178,74
학주,143,55
정서,146,71
우민,145,64
정성,170,49
승규,156,88
인용,155,86
주재,159,97
승재,181,54
주우,185,57
서수,162,97
민현,142,48
기주,178,41
민기,157,44
인주,167,44
영현,176,76
기승,147,64
용규,176,59
주유,196,67
수정,171,62
서승,166,72
성영,154,49
주유,182,46
재승,176,77
준수,170,84
철용,179,98
성현,140,59
현영,172,82
학기,175,58
승철,151,81
재인,160,88
우우,149,71
유인,151,77
주주,168,69
유서,147,43
우학,148,64
유현,156,74
수인,191,69
현학,189,92
유준,187,82
인용,153,48
규수,192,56
용승,177,76
재영,158,43
준인,144,46
용서,197,83
수학,154,44
우기,194,62
주기,184,78
기영,190,54
유준,178,49
현빈,178,86
기빈,150,50
정민,185,84
주현,151,79
기학,153,84
재성,195,49
영용,170,58
우우,190,89
규학,143,49
빈성,143,61
철우,181,64
학준,156,42
주성,194,71
성서,141,71
규학,186,78
민재,188,60
유주,170,41
용수,192,79
우서,175,81
정영,174,66
현기,185,98
주서,154,98
승승,184,83
승서,193,73
인정,196,46
유학,144,58
수승,180,93
기승,198,73
민학,146,57
승유,175,51
현주,173,94
수인,182,44
준학,146,64
재우,160,89
성기,186,52
정현,190,74
우서,176,74
서규,141,95
학성,175,48
인철,164,41
성승,169,95
용철,143,84
용성,186,45
현학,175,96
수용,140,63
승주,150,56
유우,198,57
학주,164,81
승유,155,84
영규,143,52
승주,168,63
현규,180,75
재규,142,56
주민,175,70
수빈,146,79
철규,174,47
현성,166,82
서영,186,42
현빈,181,61
승규,144,79
용승,167,42
재현,199,79
기재,186,69
수승,165,56
용정,160,83
수현,144,81
규주,193,56
정용,159,96
성성,193,55
서용,178,74
인수,179,65
빈주,188,48
수현,160,81
우용,151,68
용학,185,71
영민,186,97
수정,161,73
서준,173,51
학주,146,51
정학,197,57
준인,199,57
민유,159,53
빈승,179,50
수학,174,41
영철,140,97
주정,173,59
준학,158,45
승승,163,62
현기,177,81
재용,153,59
영현,150,83
현승,190,95
준재,197,71
유정,186,41
서용,155,96
재인,183,45
재학,184,78
재영,161,77
기준,180,69
서우,198,79
규우,153,44
승규,152,49
철학,194,71
유용,160,99
준주,140,78
수정,197,79
민주,164,63
재철,152,68
유영,170,75
철주,159,84
수서,198,55
철수,159,74
정성,171,92
빈준,141,41
민주,171,72
서재,189,54
민학,194,54
철인,169,88
빈서,181,78
성민,168,42
주빈,179,92
학승,155,53
수유,198,49
유주,168,47
용정,199,47
영민,151,68
인승,177,84
기규,199,41
재준,173,84
정현,155,89
영승,149,67
빈수,155,77
준재,174,55
용준,144,77
재수,156,74
규준,168,65
재정,197,77
정서,186,75
성빈,148,52
규영,164,75
인주,174,80
우성,186,77
철유,155,93
빈규,162,63
철서,178,98
서현,187,48
승재,188,43
정학,180,65
승수,197,60
민영,174,56
준철,195,82
영준,199,56
정현,166,90
현주,162,71
인규,158,82
영정,193,45
영정,189,95
빈기,146,84
우유,172,81
재성,168,43
현영,166,59
영규,190,74
빈용,184,70
재현,193,97
민정,147,58
준인,172,51
철준,141,60
민학,197,40
주유,167,79
용정,170,89
준준,173,90
빈학,162,83
현용,170,70
철규,194,82
민정,156,60
서수,148,63
학민,178,63
서학,191,43
용재,181,81
학재,196,84
인영,143,51
승규,168,44
영우,158,44
용철,156,75
규현,140,70
용재,151,72
용기,179,77
수현,163,65
기학,192,97
인재,173,71
승주,177,82
용철,142,50
정정,172,73
정민,198,48
영철,144,55
서빈,157,96
현서,190,74
기성,188,97
정우,163,49
유철,177,48
서규,153,56
인철,150,93
서인,144,41
승주,158,40
철승,182,98
영수,171,58
규재,160,43
서용,190,93
학준,147,94
수성,181,98
서학,155,88
주빈,158,69
정수,171,77
주준,144,94
학유,155,53
성서,169,90
수철,173,40
민성,161,87
정승,163,41
수서,173,64
철준,165,65
승철,181,83
현빈,190,55
빈수,184,61
기서,192,58
규정,155,42
철학,150,90
기인,167,86
유영,197,88
준수,153,40
성기,183,85
규빈,164,51
용규,188,88
준영,180,73
영수,199,96
철영,164,81
학현,161,75
준성,143,50
용승,181,78
승현,177,94
유철,183,91
학주,175,40
주승,191,84
빈정,197,67
민빈,143,83
우우,197,75
준학,190,78
우수,159,73
영민,180,66
빈승,182,70
영빈,142,92
빈학,177,95
규빈,164,74
현철,190,69
성빈,174,47
우서,176,71
학승,156,72
승철,179,78
주인,141,56
기용,145,65
민성,192,68
빈인,161,97
승승,149,56
수주,167,53
기철,155,67
수규,188,92
영빈,161,85
현재,151,90
수승,164,63
준빈,173,45
승빈,182,88
유영,152,89
정규,177,77
준수,199,79
수철,152,57
민유,144,70
재민,168,96
빈우,187,59
우재,161,84
학빈,166,99
민주,166,90
영승,147,50
기규,167,49
정규,173,88
승규,182,98
유현,161,45
영철,191,79
용우,144,65
인성,178,64
학재,175,72
기빈,187,48
주용,159,72
유우,164,53
정빈,164,99
승승,195,55
주철,150,58
승정,164,93
수영,189,78
승정,142,75
주승,185,94
인민,186,90
유현,173,58
정우,190,97
용학,154,86
수학,141,81
현현,179,49
수재,174,61
학성,188,90
주영,167,43
성수,162,43
우인,194,55
수정,178,94
주학,179,94
정용,189,54
준주,144,40
재빈,179,75
영성,165,89
정인,199,54
정빈,178,55
재정,188,68
규기,158,75
우정,149,49
성재,181,93
우현,189,88
용승,142,61
학철,163,52
학승,145,59
영주,195,76
준주,167,61
현기,174,86
승영,196,96
민유,174,64
정주,157,86
용정,184,83
용빈,185,85
유재,186,42
인빈,186,80
인재,180,64
우우,161,41
성규,175,90
수빈,163,55
인용,189,79
재주,140,55
민수,196,60
빈영,167,85
우영,178,88
빈빈,181,50
준용,160,99
빈서,141,96
철철,185,49
정정,177,53
기학,174,56
정규,144,70
재수,158,87
성수,145,76
영민,143,87
인재,185,74
유규,175,92
수주,159,86
학승,191,79
우규,192,68
주민,160,65
현성,186,79
민인,169,73
규성,156,74
현철,186,42
주기,175,67
유정,141,74
민수,148,49
재승,179,87
수준,141,48
영주,187,91
준우,167,80
학정,192,74
용현,143,46
철규,171,46
승수,178,53
성용,189,68
빈유,158,68
기현,160,46
우규,142,74
기영,176,52
빈규,166,95
우재,178,65
우성,153,55
준용,182,90
성서,187,61
영학,185,42
기빈,163,88
현현,150,53
주민,177,47
서준,142,61
수정,165,68
승빈,170,89
우준,147,90
철빈,161,65
서현,163,53
서주,169,96
성서,177,54
영재,189,92
유현,187,56
기기,146,98
빈기,188,70
준학,175,55
우영,149,83
현현,159,60
서영,148,49
민기,150,83
서성,174,64
우성,164,97
영용,162,90
유승,179,53
기빈,184,63
용재,143,83
빈성,169,53
기승,187,40
학서,177,65
규규,191,95
영철,162,84
정유,170,84
수인,198,40
현학,195,99
용인,162,56
용성,175,44
서승,184,94
유규,141,80
재준,197,86
성철,177,78
민재,176,90
학민,172,94
민성,171,84
성빈,143,55
규빈,182,74
서빈,142,48
영현,142,84
수승,166,64
주재,168,78
성수,188,95
준규,199,63
기인,183,76
학용,161,57
학용,157,83
승현,194,90
재우,152,87
성규,167,89
유주,142,48
현준,172,85
주재,152,85
정재,143,66
학학,159,60
성수,179,54
정용,153,52
성준,149,70

파이썬 if __name__ == "__main__" 의미

- 메인 함수의 선언, 시작을 의미합니다. 해당 코드 밑에 main 등의 함수 호출 코드를 작성해서 함수의 기능을 수행
- 직접 modex2.py 파일을 실행하는 경우에는 __name___ 변수에 __main__ 이라는 값이 할당되고 이 조건절이 참이 되어 if문 다음 문장들이 수행
- 모듈을 불러와서 사용하는 경우 __name__ 변수에는 모듈 이름이 저장되고 이 조건절이 거짓이 되어 if문 다음 문장들이 수행되지 않음
- if __name__ == "__main__"와 같이 조건문을 사용하여 터미널에서와 같이 직접 호출되어 사용될 때는 그 자체로 기능을 수행하고, 동시에 다른 모듈에서 필요한 함수 등을 제공

In [4]:
# my_module.py
#즉 모듈로 사용되는 경우랑 실행되는 경우랑 따로 하기 위해서 밑에 __name == __main 이 있는 것임.
# 모듈을 불러오거나 예로 import 할때는 바로 실행하는 것이 아니니깐 그때는 name으로 불러오게 되고
#실행하게 되면 main으로 바뀌면서 실행되게 된다.

def add(a,b):
    return a+b

def multiply(a,b):
    return a*b

# 아래 if 블록은 my_module.py가 직접 실행될 때만 실행됩니다.
if __name__ == "__main__":
    print("Module is being run directly")
    print("Add 3 + 5 =", add(3,5))
    print("Multiply 4*7 =", multiply(4,7))

Module is being run directly
Add 3 + 5 = 8
Multiply 4*7 = 28

In [8]:
import mymodule

mymodule.add_txt('a','b')

'a:b'

In [10]:
with open('modex1.py','w') as f:
    f.write(
'''
def add(a,b):
    return a + b
print(add(1,1))
''')

In [12]:
!python modex1.py

2

In [13]:
import modex1   #위에 처럼 모듈을 쓰게 되면 import만 해서 실행해도 결과값이 나오게 된다. 그렇기 때문에 위의 if 블록을 쓰는 것.

2

#### 날짜 함수

날짜와 시간을 처리하기 위한 주요 라이브러리는 datetime입니다. 이 라이브러리는 날짜, 시간, 시간대와 관련된 다양한 클래스와 함수를 제공하며, 날짜와 시간 연산에 매우 유용
- datetime.date: 날짜(연, 월, 일)를 표현하는 클래스
    - today(): 오늘의 날짜를 반환
- datetime.time: 시간(시, 분, 초, 마이크로초)을 표현하는 클래스
- datetime.datetime: 날짜와 시간을 모두 포함하는 클래스
    - now(): 현재의 날짜와 시간을 반환
- datetime.timedelta: 두 날짜/시간 간의 차이를 표현하는 클래스
- datetime.tzinfo: 시간대 정보를 위한 기본 클래스

datetime 모듈의 날짜와 시간 객체들을 문자열 형식으로 포맷팅하거나 문자열로부터 날짜와 시간 객체를 생성하기 위해 사용하는 주요 메서드는 strftime()와 strptime()
- strftime() (String Format Time)
    - 날짜와 시간 객체를 문자열로 변환하는 데 사용
    - 사용자가 지정한 형식 문자열을 기반으로 날짜와 시간 정보를 문자열로 표현
- strptime() (String Parse Time)
    - 문자열을 날짜와 시간 객체로 변환하는 데 사용
    - 주어진 형식 문자열을 기반으로 문자열에서 날짜와 시간 정보를 파싱

In [18]:
import datetime

# 현재 날짜와 시간 가져오기
now = datetime.datetime.now()
print(now)

# 오늘의 날짜만 가져오기
today = datetime.date.today()
print(today)

# 특정 날짜와 시간을 직접 지정
d = datetime.datetime(2023,11,2,14,29,45)
print(d)

# 날짜 간의 차이 계산
delta = datetime.timedelta(days=7) # 7일의 기간
new_date = today + delta
print(new_date)  # 오늘로부터 7일 후의 날짜

# 두 날짜 간의 차이 계산
date1 = datetime.date(2023,1,1)
date2 = datetime.date(2023,12,31)
diff = date2 - date1
print(diff.days)

2023-11-03 15:19:00.457809
2023-11-03
2023-11-02 14:29:45
2023-11-10
364

포맷 코드 표<BR>
포맷코드   설명   예<BR>
%a   요일 줄임말   Sun, Mon, ... Sat<BR>
%A   요일   Sunday, Monday, ..., Saturday<BR>
%w   요일을 숫자로 표시, 월요일일요일, 06   0, 1, ..., 6<BR>
%d   일   01, 02, ..., 31<BR>
%b   월 줄임말   Jan, Feb, ..., Dec<BR>
%B   월   January, February, …, December<BR>
%m   숫자 월   01, 02, ..., 12<BR>
%y   두 자릿수 연도   01, 02, ..., 99<BR>
%Y   네 자릿수 연도   0001, 0002, ..., 2017, 2018, 9999<BR>
%H   시간(24시간)   00, 01, ..., 23<BR>
%I   시간(12시간)   01, 02, ..., 12<BR>
%p   AM, PM   AM, PM<BR>
%M   분   00, 01, ..., 59<BR>
%S   초   00, 01, ..., 59<BR>
%Z   시간대   대한민국 표준시<BR>
%j   1월 1일부터 경과한 일수   001, 002, ..., 366<BR>
%U   1년중 주차, 월요일이 한 주의 시작으로   00, 01, ..., 53<BR>
%W   1년중 주차, 월요일이 한 주의 시작으로   00, 01, ..., 53<BR>
%c   날짜, 요일, 시간을 출력, 현재 시간대 기준   Sat May 19 11:14:27 2018<BR>
%x   날짜를 출력, 현재 시간대 기준   05/19/18<BR>
%X   시간을 출력, 현재 시간대 기준   '11:44:22'

In [19]:
import datetime

now = datetime.datetime.now()
print(now,type(now))
formatted = now.strftime("%Y-%m-%d %H:%M:%S")
print(formatted,type(formatted))

2023-11-03 15:22:22.814942 <class 'datetime.datetime'>
2023-11-03 15:22:22 <class 'str'>

In [23]:
import datetime

date_string = "2023-11-02 14:45:30"
print(date_string,type(date_string))
dt = datetime.datetime.strptime(date_string, "%Y-%m-%d %H:%M:%S")
print(dt, type(dt))

2023-11-02 14:45:30 <class 'str'>
2023-11-02 14:45:30 <class 'datetime.datetime'>

#### time 모듈
- 시스템 시간에 접근하거나 간단한 타이머 기능을 구현
- 함수와 같이 프로그램을 일정 시간 동안 중지시키는 데 사용
- 시간을 연도, 월, 일, 시, 분, 초 등의 구성 요소로 변환하고 다룰 수 있는 struct_time 객체를 제공
- time 모듈은 날짜와 시간을 처리하는 다양한 프로그래밍 요구에 대응할 수 있는 기본적인 기능을 제공하지만, 더 복잡한 날짜 시간 처리나 시간대 변환 등은 datetime 모듈 또는 외부 라이브러리를 사용

In [ ]:
# localtime() 함수는 파이썬의 time 모듈에 포함되어 있으며, 이 함수는 초로 표시되는 시간을 구조화된 시간 튜플 형태로 변환하여 반환

In [25]:
import time

local_time = time.localtime()
print(local_time)

time.struct_time(tm_year=2023, tm_mon=11, tm_mday=3, tm_hour=15, tm_min=34, tm_sec=15, tm_wday=4, tm_yday=307, tm_isdst=0)

In [26]:
# 현재 시간을 1970년 1월 1일 0시 0분 0초 (유닉스 시간의 시작)부터 현재까지의 초(second)로 표현한 값을 반환
import time
time.time()

1698993397.0878751

In [27]:
# 초로 표현된 시간을 구조화된 시간 튜플 형태로 변환
t = time.time()
time.localtime(t)

time.struct_time(tm_year=2023, tm_mon=11, tm_mday=3, tm_hour=15, tm_min=37, tm_sec=50, tm_wday=4, tm_yday=307, tm_isdst=0)

In [28]:
# strftime 함수는 시간에 관계된 것을 세밀하게 표현할 수 있는 여러 가지 포맷 코드 제공
# time.localtime() 함수는 초로 표현된 시간을 구조화된 시간 튜플 형태로 변환
import time
d = time.strftime('%d', time.localtime(time.time()))
m = time.strftime('%m', time.localtime(time.time()))
y = time.strftime('%Y', time.localtime(time.time()))
a = time.strftime('%A', time.localtime(time.time())) #요일
print(d)
print(m)
print(y)
print(a)

03
11
2023
Friday

In [32]:
import time
current_time = time.localtime(time.time())
print(current_time)
# struct_time 객체를 인간이 읽을 수 있는 형태로 변환합니다.
readable_time = time.asctime(current_time)  ##############
print(readable_time)

time.struct_time(tm_year=2023, tm_mon=11, tm_mday=3, tm_hour=15, tm_min=47, tm_sec=30, tm_wday=4, tm_yday=307, tm_isdst=0)
Fri Nov  3 15:47:30 2023

In [35]:
# asctime() 함수는 주어진 시간 튜플을 "Thu Nov 2 14:59:45 2023"와 같은 형식의 문자열로 변환
import time
t = time.localtime(1609160537.371015)
print(type(t))
at = time.asctime(t)
print(at, type(at))

<class 'time.struct_time'>
Mon Dec 28 22:02:17 2020 <class 'str'>

In [34]:
# Q. 11609160537.371015을 "Mon Dec 28 22:02:17 2020" 포멧으로 출력하세요.

print(time.strftime('%a %b %d %H:%M:%S %Y',time.localtime(1609160537.371015)))
print(time.asctime(time.localtime(1609160537.371015)))

Mon Dec 28 22:02:17 2020
Mon Dec 28 22:02:17 2020

In [37]:
# Q. 현재 날짜와 시간을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.
print(time.asctime(time.localtime(time.time())))

Fri Nov  3 16:03:40 2023

In [38]:
# timestamp -> str
import time

t = time.time()

print(t,type(t))
s = str(t)
print(s,type(s))

1698995192.8857386 <class 'float'>
1698995192.8857386 <class 'str'>

In [42]:
# timestamp -> datetime
from datetime import datetime
t = time.time()
print(t,type(t))
d = datetime.fromtimestamp(t)
print(d,type(d))

1698995415.0895154 <class 'float'>
2023-11-03 16:10:15.089515 <class 'datetime.datetime'>

In [43]:
# timestamp -> datetime -> str
# Q. 현재 시간을 년-월-일 시:분:초로 출력하세요.
import time
from datetime import datetime
t = time.time()
d = datetime.fromtimestamp(t) # timestamp -> datetime
s = d.strftime('%Y-%m-%d %X') # datetime -> str
s

'2023-11-03 16:12:45'

In [44]:
# datetime -> str
from datetime import datetime

s = datetime.now()
print(s, type(s))

s1 = s.strftime('%Y-%m-%d %H:%M:%S')
print(s1, type(s1))

2023-11-03 16:16:05.919231 <class 'datetime.datetime'>
2023-11-03 16:16:05 <class 'str'>

In [45]:
# str -> datetime
from datetime import datetime
s = '2021-07-20 11:13:58'
print(s, type(s))
d = datetime.strptime(s,'%Y-%m-%d %H:%M:%S')
print(d,type(d))

2021-07-20 11:13:58 <class 'str'>
2021-07-20 11:13:58 <class 'datetime.datetime'>

In [46]:
# str -> datetime -> timestamp
s = '2021-07-20 11:13:58'
timestamp = time.mktime(datetime.strptime(s,'%Y-%m-%d %H:%M:%S').timetuple()) #time.mktime(datetime).timetuple()
print(timestamp, type(timestamp))

1626747238.0 <class 'float'>

In [47]:
# datetime -> timestamp
d = datetime.today()
print(d,type(d))
timestamp = time.mktime(d.timetuple())
print(timestamp, type(timestamp))

2023-11-03 16:23:58.524207 <class 'datetime.datetime'>
1698996238.0 <class 'float'>

#### 파이썬에서 언더바/더블언더바 의 의미와 역할

단일 언더바 (_):

- 인터프리터: 파이썬 인터프리터에서 단일 언더바는 가장 최근의 표현식의 결과를 저장
- 변수 이름: 관례적으로 관심이 없는 값을 할당할 때 사용합니다. 예를 들어, for _ in range(5):는 반복문에서 인덱스를 사용하지 않을 때 관용적으로 사용
- 국제화(i18n)/지역화(l10n): 함수 이름으로서 _()는 종종 gettext 모듈을 통해 문자열을 번역하는 데 사용
- 값 무시: 튜플 언패킹에서 특정 값을 무시할 때 사용합니다. 예: x, _, y = (1, 2, 3) 여기서 2는 무시

단일 선행 언더바 (_변수):
- 일반적으로 모듈 내부에서만 사용되는 "private" 변수나 함수 또는 메서드를 지정할 때 사용
- 파이썬에서 강제할 수는 없지만, 이것은 프로그래머에게 그 변수나 함수가 내부 사용을 위한 것임을 알려주는 관례

단일 후행 언더바 (변수_):
- 파이썬 키워드와 충돌을 피하기 위해 사용됩니다. 예를 들어, class_는 class라는 이름 대신 사용

더블 선행 언더바 (__변수):
- 클래스의 속성을 이름 맹글링(name mangling)하기 위해 사용
- 이는 속성이 해당 클래스와 그 서브클래스 내부에서만 사용될 것임을 나타내며, 부모 클래스의 필드와 이름 충돌을 피하는 데 도움을 준다. 예: __private_var는 _ClassName__private_var로 변환되어 클래스 외부에서 직접 접근할 수 없습니다.

더블 선행과 후행 언더바 (변수):
- 파이썬의 매직 메서드 또는 특별 메서드를 나타냅니다. 이들은 특별한 의미를 가지며, 파이썬의 내부 구조와 연동
- 예를 들어, __init__, __call__, __str__, __repr__ 등이 있습니다. 이러한 메서드들은 사용자 정의 객체가 내장 타입과 상호작용하는 방식을 정의 <br>
    __init__: 객체가 생성될 때 초기화를 담당합니다.<br>
    __repr__: 객체의 “공식적인” 문자열 표현을 제공합니다.<br>
    __add__: + 연산자로 두 객체를 더할 때 호출됩니다.<br>
    __call__: 객체를 함수처럼 호출할 수 있게 합니다 (예: instance()).<br>
    __getitem__: 인덱싱을 통해 요소에 접근할 때 호출됩니다 (예: instance[key]).
- __main__은 파이썬에서 사용되는 특별한 변수이며, 현재 최상위 실행 환경이 무엇인지를 나타내는 데 사용됩니다. 파이썬 스크립트가 직접 실행될 때 그 스크립트의 __name__ 변수는 "__main__"으로 설정

In [3]:
for _ in range(5):
    print(_)

0
1
2
3
4

In [4]:
# 리스트의 각 아이템이 튜플 형태를 이루고 있어야 함
for i, _ in [(1,'a'),(2,'b'),(3,'c'),(6,'d'),(5,'e')]:
    print(f'{i}번 : {_}')

1번 : a
2번 : b
3번 : c
6번 : d
5번 : e

In [5]:
for i,_ in enumerate([1,2,3,4,5]):
    print(f'{i}번 : {_}')

0번 : 1
1번 : 2
2번 : 3
3번 : 4
4번 : 5

In [6]:
# _InternalUse 클래스와 _internal_method 메서드, 그리고 _internal_function 함수는 모두 단일 선행 언더바를 사용하여 정의
# 이것은 이들이 모듈 내부에서만 사용되도록 의도
class _InternalUse:
    def __init__(self):
        print("이 클래스는 내부적으로만 사용됩니다.")
        
    def _internal_method(self):
        print("이 메서드는 내부적으로만 사용됩니다.")

def _internal_function():
    print("이 함수는 내부적으로만 사용됩니다.")

In [7]:
# class는 파이썬에서 클래스를 정의할 때 사용하는 키워드입니다. 만약 변수로 class를 사용하고 싶다면,
# 이름 충돌을 피하기 위해 후행 언더바를 사용
class_ = "This is a string variable, not a class."

# from_은 파이썬의 from 키워드와 충돌하지 않도록 하기 위해 후행 언더바를 붙여서 사용
def send_email(address, from_):
    print(f"ㄴ두야ㅜㅎ 드먀ㅣ 새 {address} from (from_)")

In [ ]:
# __privateVar와 __privateMethod는 클래스 Test 내부에서만 사용될 것이라는 의미로 이름 앞에 더블 언더바를 붙였습니다. 
# 파이썬 인터프리터는 이 이름들을 _Test__privateVar와 _Test__privateMethod로 맹글링하여 내부적으로 사용합니다. 
# 따라서 이들에 대한 직접적인 접근은 에러를 발생
class Test:
    def __init__(self):
        self.__privateVar = 42

    def __privateMethod(self):
        return "This is a private method"

# 외부에서 접근
test = Test()
# print(test.__privateVar)  # 이 코드는 에러를 발생시킵니다.
# print(test.__privateMethod())  # 이 코드도 에러를 발생시킵니다.

In [1]:
# 파이썬 인터프리터에서 가장 마지막 표현식의 결과값을 자동적으로 "_"에 저장
5+4

9

In [2]:
_

9

#### 파이썬에서 -1은 다양한 방식으로 사용됩니다. 다음은 일부 예시입니다:

- 인덱스: 파이썬에서는 리스트, 문자열, 튜플 등의 시퀀스 자료형의 인덱스를 지정할 때 음수를 사용할 수 있습니다. 이때 -1은 시퀀스의 마지막 요소를 가리킵니다. 예를 들어, 리스트에서 my_list[-1]은 리스트의 마지막 요소를 반환합니다.

- 슬라이스: 마찬가지로, 시퀀스 자료형의 슬라이스를 지정할 때도 음수를 사용할 수 있습니다. 이때 -1은 시퀀스의 마지막 요소를 가리킵니다. 예를 들어, 리스트에서 my_list[:-1]은 마지막 요소를 제외한 모든 요소를 반환합니다.

- 반환 값: 일부 함수에서는 실패 또는 오류를 나타내는 값을 -1로 반환합니다. 예를 들어, 문자열에서 find() 메서드는 문자열에서 지정된 문자열을 찾을 수 없을 때 -1을 반환합니다.

- 비트 연산: 비트 연산에서는 -1이 모든 비트가 1인 이진수로 사용됩니다. 예를 들어, 0b11111111은 10진수로 255이며, -1과 같습니다.